/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleHelloWorld;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    protected void doGet(HTTPServletRequest request, HTTPServletResponse response){
        throws servletException, IOException{
            response.sendRedirect(request.getParameter("target"));
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
